# Generated by Django 3.2.4 on 2021-06-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Anonymous', max_length=14, verbose_name='Name')),
                ('body', models.CharField(db_index=True, default='', max_length=140, verbose_name='Body')),
                ('image', models.CharField(db_index=True, default='Anonymous', max_length=1000, verbose_name='image')),
                ('like_count', models.PositiveIntegerField(blank=True, default=0, verbose_name='Like Count')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created Datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Datetime')),
            ],
        ),
    ]
